baseURL = 'https://safe049.github.io/'
languageCode = 'zh'
title = 'Dysprosium'
theme = "hugo-theme-m10c"
disqusShortname = "safe049"

sectionPagesMenu = 'main'
[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 2
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 3
[params]
  author = "Dysprosium"
  description = "最好的描述就是没有描述"
  avatar = 'https://t.tutu.to/img/alNlI'
  favicon = 'https://t.tutu.to/img/alNlI'
  menu_item_separator = " | "
  [[params.social]]
    icon = "brand-github"
    name = "Github"
    url = "https://github.com/safe049"
  [[params.social]]
    icon = "mail"
    name = "Email"
    url = "mailto:1329261154@qq.com"
[params.gitalk] 
    clientID = "Ov23liC6ph1S4hZi41Fw" # 您刚才创建Github Application 的 Client ID
    clientSecret = "a7d5b81f218e2c8cca10664ef0e726acd228248e" # 您刚才创建Github Application 的 Client Secret
    repo = "safe049.github.io" # 您的博客的github地址Repository name，例如：xxxx.github.io
    owner = "safe049" # 您的GitHub ID
    admin= "safe049" # 您的GitHub ID
    id= "https://safe049.github.io/post/" # 文章页面的链接地址就是ID
    labels= "gitalk" # Github issue labels. If you used to use Gitment, you can change it
    perPage= 15 # Pagination size, with maximum 100.
    pagerDirection= "last" # Comment sorting direction, available values are 'last' and 'first'.
    createIssueManually= true # 设置为true，如果是管理员登录，会自动创建issue，如果是false，需要管理员手动添加第一个评论(issue)
    distractionFreeMode= false # Enable hot key (cmd|ctrl + enter) submit comment.
