baseURL = 'https://safe049.github.io/'
languageCode = 'zh'
title = 'Dysprosium'
theme = "hugo-theme-m10c"

sectionPagesMenu = 'main'
[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 2
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 3
[params]
  author = "Dysprosium"
  description = "最好的描述就是没有描述"
  avatar = 'https://t.tutu.to/img/alNlI'
  favicon = 'https://t.tutu.to/img/alNlI'
  menu_item_separator = " | "
  [[params.social]]
    icon = "brand-github"
    name = "Github"
    url = "https://github.com/safe049"
  [[params.social]]
    icon = "mail"
    name = "Email"
    url = "mailto:1329261154@qq.com"
[params.gitalk] 
    clientID = "Ov23liC6ph1S4hZi41Fw" # 您刚才创建Github Application 的 Client ID
    clientSecret = "a7d5b81f218e2c8cca10664ef0e726acd228248e" # 您刚才创建Github Application 的 Client Secret
    repo = "safe049.github.io" # 您的博客的github地址Repository name，例如：xxxx.github.io
    owner = "safe049" # 您的GitHub ID
    admin= "safe049" # 您的GitHub ID